### ISSUE TITLE
Playing Bootcamp

### ISSUE THREAD

**Issue by MayoHighSchoolPlanetarium** [charlesveasey/FulldomeBootcamp#1]
Mr. Veasey,

I run a planetarium for a public school district in Minnesota. I have been telling students that I would like to play video games on the dome. This is a way for me to get them into the planetarium and start being interested in the content I teach. I have been trying to get your FulldomeBootcamp to play with no success. How do I get this game, and your other ones, to play on my dome? I appreciate your time in helping me entice a new generation of children into science and space.

Thanks,

Paul L

**Comment by charlesveasey** [comment]
Hi Paul,

The Bootcamp demo no longer functions in Unity 5. However, the
UnityDomemaster plugin can be used to turn most 3D games into a domemaster.

To get real-time applications on the dome you'll need a capable dome
program and a way to communicate between applications.

What is your current dome configuration (i.e. number of projectors,
software, etc.)

best,
Charles

**Comment by MayoHighSchoolPlanetarium** [comment]
Charles,
Thanks for the prompt reply. I am new to the digital, fulldome world; learning as I go. I have a system built by the Elumenati group (http://www.elumenati.com/). I have a Barco projector that displays 360 degrees fulldome with 2560 x 1600 resolution. So that makes my dome 1600 x 1600? I have a 30-foot, fixed dome. The computer is a newly built Alienware machine. I am not exactly sure about the exact specifications within the machince, but could probably figure it out. I use the Uniview scaling software/database to fly around the universe; I use Stellarium for the star field. I have a piece of software called WorldViewer to supposedly display flat content on the round dome, as well as Science On A Sphere content. But, that software is giving me issues because the default geometry is all off and I am not getting much support to straighten it out. I would like a capable dome program that allows me to put live websites, GoogleEarth, Youtube clips, standard movies, PowerPoint, Prezi, images, ...etc on the dome in real time.

That would all be cool, but I contacted you about a video game. Do any of those video games you have still work on the dome? I am interested to hear how you might be able to help me out. This is an awesome way to get young students excited about science and engineering. I have students stopping in all the time to see what I am working on.

Thanks for your time,

Paul L

**Comment by charlesveasey** [comment]
Ok. This should be easy for you since you have a single projector with a fisheye lens.

For gaming, I'd recommend to get started with Unity 5. It's easy to use and great for students to make their own games. It's also free.
https://unity3d.com/

Download the UnityDomemaster addon
https://github.com/charlesveasey/UnityDomemaster

and follow the readme or run the examples scenes within the UnityDomemaster project.

Then simply drag the game window (tab) to the dome (assuming your second monitor). Or build the game and select the second display in the popup window.

One way you can get anything onto the dome is by using a capture card and another computer. The display of one computer feeds into the capture card on your dome machine. With this you can place the capture input onto a plane in Unity or some other program and move it around the dome. 

You basically just need a fisheye output which is what the dome tools do on the InteractiveDome website. 

Feel free to follow up.

**Comment by MayoHighSchoolPlanetarium** [comment]
Charles,

Do any of your other games still work on the dome?

I will be experimenting with your suggestions when I get some free time.

Thank you,

Paul Larson
Planetarium Director
palarson@rochester.k12.mn.usmailto:palarson@rochester.k12.mn.us
507-328-5600

[RPSLogo]

**Comment by MayoHighSchoolPlanetarium** [comment]
Charles,

Do you have a URL available for DomeBreaker and/or FulldomeSpaceShooter that I could access to play those games on my dome? I have been working with Unity and your files and can't figure out how to get the games to actually play. I was able to get your dome version of SpaceShooter to play on my home computer, but the physics weren't working in that the ship would fly right through the asteroids and enemy ships. This two games would be perfect to start out in the dome for students while we work on making our own games.

Anything you cold provide would be awesome.

Thanks,

Paul Larson
Planetarium Director
Rochester Public Schools

palarson@rochester.k12.mn.us

507-328-5500
